routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Laravel\Socialite\Facades\Socialite;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'auth'], function () {
    Route::get('/', function () {
        return view('welcome');
    });

    Route::get('/articles', 'LandingController@article')->name('articles');
    Route::get('/users', 'LandingController@user')->name('users');
    Route::get('/employees', 'LandingController@employee')->name('employees');
    Route::get('/messages', 'LandingController@usersMessages')->name('messages');
    Route::get('/messages/{id}','MessageController@userMessages')->name('userMessages');
});

Route::resource("articulo",ArticleController::class);
Route::resource("usuario",UserController::class);
Route::resource("mensaje",MessageController::class);
Route::get('/login-google', function () {
    return Socialite::driver('google')->redirect();
});

Route::get('/google-callback', function () {
    $user = Socialite::driver('google')->user();

});
require __DIR__. '/auth.php';

resources/views/partials/articles.blade.php
@extends('layouts.menu')
@section('content')
    <section class="py-5">
        <div class="container px-4 px-lg-5 mt-5">
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            @foreach($articles as $article)
                <!-- Section-->
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Product image-->
                            <img class="card-img-top" src="storage/img/{{$article->id}}-article.jpg" alt="..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">{{$article->name}}</h5>
                                    <!-- Product price-->
                                    ${{$article->price}}<br>
                                    <strong>Category:</strong> {{$categories[$article->category_id-1]->name}}

                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center">
                                    <form method="post" action="{{route("articulo.destroy", $article->id)}}">
                                        @csrf
                                        @method('DELETE')
                                        <button class="btn btn-outline-danger mt-auto">DELETE</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                @endforeach
                {{$articles->links()}}
            </div>
        </div>
    </section>
@endsection

resources/views/partials/employees.blade.php
@extends('layouts.menu')
@section('content')
    <section class="py-5">
        <div class="container px-4 px-lg-5 mt-5">
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            @foreach($employees as $employee)
                <!-- Section-->
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Product image-->
                            <img class="card-img-top" src="storage/img/employee.png" alt="..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">{{$employee->name}}</h5>
                                    <!-- Product price-->
                                    ${{$employee->email}}<br>
                                </div>
                            </div>
                        </div>
                    </div>
                @endforeach
                {{$employees->links()}}
            </div>
        </div>
    </section>
@endsection

resources/views/partials/footer.blade.php
<!-- Footer-->
<footer class="py-5 bg-dark">
    <div class="container px-4 px-lg-5"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2021</p></div>
</footer>

resources/views/partials/messages.blade.php
@extends('layouts.menu')
@section('content')
    <section class="py-5">
        <div class="container px-4 px-lg-5 mt-5">
            <div class="col-sm-12 col-md-12 col-lg-12">
                <table class="table table-striped">
                    <thead class="bg-dark text-white">
                        <tr>
                            <th>ID</th>
                            <th>Contenido del mensaje</th>
                            <th>A quien va</th>
                            <th>Denunciado</th>
                            <th>Borrar</th>
                        </tr>
                    </thead>
                    <tbody>
                    @foreach($messages as $message)

                        <tr>
                            <td>{{ $message->id }}</td>
                            <td>{{ $message->message }}</td>
                            <td>{{ $message->reciever()->first()->name }}</td>
                            <td class="text-center">
                                @isset($message->reports()->get()->first()->message_id)
                                    <i class="fs-5 text-danger bi bi-exclamation-triangle-fill"></i>
                                @endisset
                            </td>
                            <td><div class="text-center">
                                    <form method="post" action="{{route("mensaje.destroy", $message->id)}}">
                                        @csrf
                                        @method('DELETE')
                                        <button class="btn btn-outline-danger mt-auto">DELETE</button>
                                    </form>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </section>
@endsection

resources/views/partials/nav.blade.php
<!-- Responsive navbar-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container px-5">
        <a class="navbar-brand" href="/">BatoiPop</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link" aria-current="page" href="/employees">Empleados</a></li>
                <li class="nav-item"><a class="nav-link" href="/users">Users</a></li>
                <li class="nav-item"><a class="nav-link" href="/articles">Articulos</a></li>
                <li class="nav-item"><a class="nav-link" href="/messages">Mensajes</a></li>
                @if(Auth::user())
                    <li class="nav-item"><i></i><a class="nav-link active" href="/logout">Logout {{Auth::user()->name}}</a></li>
                @else
                    <li class="nav-item"><a class="link-light active" href="/login"><i class="fs-4 bi bi-egg-fried"></i></a></li>
                @endif
            </ul>
        </div>
    </div>
</nav>

resources/views/partials/users.blade.php
@extends('layouts.menu')
@section('content')
    <section class="py-5">
        <div class="container px-4 px-lg-5 mt-5">
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            @foreach($users as $user)
                <!-- Section-->
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Product image-->
                            <img class="card-img-top" src="storage/img/seducsion.jpg" alt="..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">{{$user->name}}</h5>
                                    <!-- Product price-->
                                    {{$user->email}}<br>

                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center">
                                    <form method="post" action="{{route("usuario.destroy", $user->id)}}">
                                        @csrf
                                        @method('DELETE')
                                        <button class="btn btn-outline-danger mt-auto">DELETE</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                @endforeach
                {{$users->links()}}
            </div>
        </div>
    </section>
@endsection

resources/views/partials/usersMessages.blade.php
@extends('layouts.menu')
@section('content')
    <section class="py-5">
        <div class="container px-4 px-lg-5 mt-5">
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            @foreach($users as $user)
                <!-- Section-->
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Product image-->
                            <img class="card-img-top" src="storage/img/seducsion.jpg" alt="..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">{{$user->name}}</h5>
                                    <!-- Product price-->
                                    ${{$user->email}}<br>

                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center">
                                    <a class="btn btn-outline-primary mt-auto" href="/messages/{{ $user->id }}">Ver Mensajes</a>
                                </div>
                            </div>
                        </div>
                    </div>
                @endforeach
                {{$users->links()}}
            </div>
        </div>
    </section>
@endsection